name: brtbus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter:
  geolocator: ^5.2.0
  flutter_polyline_points: ^0.1.0
  http: ^0.12.0+2
  permission:
  sliding_up_panel: ^0.3.6
  latlong: ^0.6.1
  gradient_app_bar: ^0.0.1
  material_design_icons_flutter: ^3.4.4895
  simple_animations: ^1.3.0
  flutter_bloc: ^3.2.0
  url_launcher: ^5.4.10
  splashscreen: ^1.2.0
  flutter_svg: ^0.17.4

  # firebase_admob: ^0.9.0+10

dependency_overrides:
  flutter_offline: ^0.3.0
  connectivity: ^0.4.8+2

  #compileSdkVersion 28

# The following adds the Cupertino Icons font to your application.
# Use with the CupertinoIcons class for iOS style icons.

cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - images/png/
    - images/svg/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Light.ttf
        - weight: 300
        - asset: fonts/Montserrat-Regular.ttf
        - weight: 400

        - asset: fonts/Montserrat-LightItalic.ttf
        - asset: fonts/Montserrat-ExtraLightItalic.ttf
        - weight: 300
        - style: italic

        - asset: fonts/Montserrat-ExtraBold.ttf
        - asset: fonts/Montserrat-Bold.ttf
        - weight: 700

        - asset: fonts/Montserrat-BoldItalic.ttf
        - asset: fonts/Montserrat-ExtraBoldItalic.ttf
        - weight: 700
        - style: italic

        - asset: fonts/Montserrat-SemiBold.ttf
        - weight: 600
        - asset: fonts/Montserrat-SemiBoldItalic.ttf
        - weight: 600
        - style: italic

        - asset: fonts/Montserrat-Thin.ttf
        - weight: 100
        - asset: fonts/Montserrat-ThinItalic.ttf
        - weight: 100
        - style: italic

        - asset: fonts/Montserrat-Medium.ttf
        - weight: 500
        - asset: fonts/Montserrat-MediumItalic.ttf
        - weight: 500
        - style: italic

        - asset: fonts/Montserrat-Black.ttf
        - weight: 900

        - asset: fonts/Montserrat-BlackItalic.ttf
        - weight: 900
        - style: italic

  uses-material-design: true
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
